[package]
name = "friends-connect-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
friends-connect = { path = "../.." }
tokio = { version = "1.0", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }